---
apiVersion: v1
kind: ConfigMap
metadata:
  name: explora-kafka-env
  labels:
    app: explora-kafka
data:
  METRICS: 'airquality.no2::number,airquality.pm10::number'
  READINGS_TOPIC: 'airquality'
  APP_NAME: 'explora-kafka-ingestion'
  KBROKERS: '10.10.139.32:9092'
  GEO_INDEX: 'quadtiling'
  PRECISION: '14'
  #REST_ENDPOINT_HOSTNAME: '0.0.0.0'
  REST_ENDPOINT_PORT: '7070'

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: explora-kafka
  name: explora-kafka
spec:
  replicas: 3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: explora-kafka
    spec:
      containers:
      - env:
        - name: REST_ENDPOINT_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        envFrom:
        - configMapRef:
            name: explora-kafka-env
        image: gitlab.ilabt.imec.be:4567/lordezan/explora-kafka:latest
        command: ["sh"]
        args: ["-c", "java -cp /usr/local/service/explora-kafka-0.1-jar-with-dependencies.jar ingestion.IngestStream --metric-list ${METRICS} --geo-index ${GEO_INDEX} --precision ${PRECISION} --cleanup"]
        name: explora-kafka
        resources:
          requests:
            cpu: "0.5"
          limits:
            cpu: "2"
        ports:
        - containerPort: 7070
          name: explora-kafka
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
status: {}
